### ISSUE TITLE
Unclear authorship

### ISSUE THREAD

**Issue by xHire** [marvindanig/potion-of-flight#1]
Hi! Quite interesting project. :·) There’s just one thing that I think should be covered. Right now, the page of the book makes it sound like David Revoy made it (e.g., wording “@davidrevoy's original work”). I think it collides with a [requirement of not making an attribution sound like an endorsement](https://www.peppercarrot.com/en/static14/documentation&page=950_License_attribution_good_practise). Could you please make it a bit clearer who is author of what? Thanks! :·)

**Comment by marvindanig** [comment]
Agreed. I have to review the source code of this repository as well. Will take it up early next week.

**Comment by marvindanig** [comment]
Fixed. 

- Authorship updated
- License updated
- Source updated
